version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: bookingsystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - room-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: backend
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookingsystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - room-net

networks:
  room-net:

volumes:
  postgres_data: